### ISSUE TITLE
Getting error doing pip install sqython

### ISSUE THREAD

**Issue by MaximoTrinidad** [XamNalpak/SQython#1]
Hi @XamNalpak ,

Not sure what I'm doing wrong.   I have my Linux WSL2 environment set to use Anaconda
```
base) maxt@mxtlpt01:/mnt/c/Users/max_t$ python --version
Python 3.7.6
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ conda --version
conda 4.10.1
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Error message**
```
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ pip install sqython
Collecting sqython
  Using cached SQython-0.0.4.tar.gz (3.5 kB)
Collecting psycopg2
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/maxt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3jknbzy1/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3jknbzy1/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3jknbzy1/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-3jknbzy1/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-3jknbzy1/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /tmp/pip-install-3jknbzy1/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-3jknbzy1/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-3jknbzy1/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-3jknbzy1/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by XamNalpak** [comment]
That’s interesting. I just use the base python environment. Have you tried
making a virtual environment and then installing ?

 Cheers.


Also I found a bug and updated to .0.0.4

pip install SQython —upgrade


I also have not used Linux in a while !

**Comment by XamNalpak** [comment]
So after reading this error there seems to be something wrong with Psycopg2. I believe this is an error on your side and not ours. Ill attach a screen shot of me successfully installing.

If you happen to figure this out please please please let us know!!

![Capture](https://user-images.githubusercontent.com/75277029/120019610-a9e14d00-bfb6-11eb-9496-dc635e3fea06.JPG)

**Comment by XamNalpak** [comment]
@MaximoTrinidad 

https://stackoverflow.com/questions/5420789/how-to-install-psycopg2-with-pip-on-python

This link should answer everything you have about psycopg2 and Linux.

**Comment by MaximoTrinidad** [comment]
@XamNalpak 

So, the issue is in Linux. I got both my Windows and Linux loaded with the same packages so  I can move notebooks between them.

```

(base) PS C:\WINDOWS\system32> pip install SQython
Collecting SQython
  Downloading SQython-0.0.4.tar.gz (3.5 kB)
Requirement already satisfied: psycopg2 in c:\programdata\anaconda3\lib\site-packages (from SQython) (2.8.6)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from SQython) (1.20.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from SQython) (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas->SQython) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas->SQython) (2021.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->SQython) (1.15.0)
Building wheels for collected packages: SQython
  Building wheel for SQython (setup.py) ... done
  Created wheel for SQython: filename=SQython-0.0.4-py3-none-any.whl size=3701 sha256=f12435a5be5d662f2f0f785abf9b99cb33a524c0135484362048872f624c3aa4
  Stored in directory: c:\users\max_t\appdata\local\pip\cache\wheels\ba\61\7e\0aa9a8aad83ca518ad02736dce399f82567326cedc3c992702
Successfully built SQython
Installing collected packages: SQython
Successfully installed SQython-0.0.4
(base) PS C:\WINDOWS\system32>
```

**Comment by XamNalpak** [comment]
@MaximoTrinidad Yes !! Awesome. Would you like linux compatability ? i can try to add more dependencies right now.

**Comment by MaximoTrinidad** [comment]
I updated the issue. It's LInux!

Maximo Trinidad
Microsoft MVP - Cloud and Datacenter Management (PowerShell)



________________________________

**Comment by MaximoTrinidad** [comment]
@XamNalpak 
> @MaximoTrinidad Yes !! Awesome. Would you like linux compatability ? i can try to add more dependencies right now.

YES! That would be great. Cross-platform usage is key nowadays! This is why I'm uising both on WSL2 and Windows. 

:)

**Comment by XamNalpak** [comment]
@MaximoTrinidad version 0.0.5 is out with the psycopg2 BINARY package added as a dependency. Should work now.

**Comment by MaximoTrinidad** [comment]
I will try again aan post back in a few minutes. 

Thx

**Comment by MaximoTrinidad** [comment]
@XamNalpak 

It did not wok for me. But due to my experience trying to mak SQL Alchemy work. i went back and install an the older version of psycopg2==2.7.7

Then, I can do "pip install sqython"
It's strange but it WORKS!
```
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ pip install psycopg2==2.7.7
Collecting psycopg2==2.7.7
  Downloading psycopg2-2.7.7-cp37-cp37m-manylinux1_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 1.2 MB/s
Installing collected packages: psycopg2
Successfully installed psycopg2-2.7.7
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ pip install sqython
Collecting sqython
  Using cached SQython-0.0.5.tar.gz (3.7 kB)
Requirement already satisfied: psycopg2 in /home/maxt/anaconda3/lib/python3.7/site-packages (from sqython) (2.7.7)
Requirement already satisfied: numpy in /home/maxt/anaconda3/lib/python3.7/site-packages (from sqython) (1.18.1)
Requirement already satisfied: pandas in /home/maxt/anaconda3/lib/python3.7/site-packages (from sqython) (1.0.1)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.8.6-cp37-cp37m-manylinux1_x86_64.whl (3.0 MB)
Requirement already satisfied: pytz>=2017.2 in /home/maxt/anaconda3/lib/python3.7/site-packages (from pandas->sqython) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/maxt/anaconda3/lib/python3.7/site-packages (from pandas->sqython) (2.8.1)
Requirement already satisfied: six>=1.5 in /home/maxt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->sqython) (1.14.0)
Building wheels for collected packages: sqython
  Building wheel for sqython (setup.py) ... done
  Created wheel for sqython: filename=SQython-0.0.5-py3-none-any.whl size=3848 sha256=eb25f8d3f4b5ad57dd6314477666938599053eacc097ea2d555d4234aa5fa3ab
  Stored in directory: /home/maxt/.cache/pip/wheels/9a/d7/a0/e42ee9a671867b6072bc7ba26aa77fe01263294415b729af36
Successfully built sqython
Installing collected packages: psycopg2-binary, sqython
Successfully installed psycopg2-binary-2.8.6 sqython-0.0.5
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$
```

(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ pip install psycopg2==2.7.7
Collecting psycopg2==2.7.7
  Downloading psycopg2-2.7.7-cp37-cp37m-manylinux1_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 1.2 MB/s
Installing collected packages: psycopg2
Successfully installed psycopg2-2.7.7
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$ pip install sqython
Collecting sqython
  Using cached SQython-0.0.5.tar.gz (3.7 kB)
Requirement already satisfied: psycopg2 in /home/maxt/anaconda3/lib/python3.7/site-packages (from sqython) (2.7.7)
Requirement already satisfied: numpy in /home/maxt/anaconda3/lib/python3.7/site-packages (from sqython) (1.18.1)
Requirement already satisfied: pandas in /home/maxt/anaconda3/lib/python3.7/site-packages (from sqython) (1.0.1)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.8.6-cp37-cp37m-manylinux1_x86_64.whl (3.0 MB)
Requirement already satisfied: pytz>=2017.2 in /home/maxt/anaconda3/lib/python3.7/site-packages (from pandas->sqython) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/maxt/anaconda3/lib/python3.7/site-packages (from pandas->sqython) (2.8.1)
Requirement already satisfied: six>=1.5 in /home/maxt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->sqython) (1.14.0)
Building wheels for collected packages: sqython
  Building wheel for sqython (setup.py) ... done
  Created wheel for sqython: filename=SQython-0.0.5-py3-none-any.whl size=3848 sha256=eb25f8d3f4b5ad57dd6314477666938599053eacc097ea2d555d4234aa5fa3ab
  Stored in directory: /home/maxt/.cache/pip/wheels/9a/d7/a0/e42ee9a671867b6072bc7ba26aa77fe01263294415b729af36
Successfully built sqython
Installing collected packages: psycopg2-binary, sqython
Successfully installed psycopg2-binary-2.8.6 sqython-0.0.5
(base) maxt@mxtlpt01:/mnt/c/Users/max_t$
